class _NumericMaterialLocalizations implements MaterialLocalizations {\n  final MaterialLocalizations original;\n  _NumericMaterialLocalizations(this.original);\n\n  @override\n  String formatMonthYear(DateTime date) {\n    final m = date.month.toString().padLeft(2, '0');\n    return ' / ';\n  }\n\n  @override\n  String formatMediumDate(DateTime date) {\n    final d = date.day.toString().padLeft(2, '0');\n    final m = date.month.toString().padLeft(2, '0');\n    return ' /  / ';\n  }\n\n  @override\n  String formatShortMonth(int monthIndex) {\n    return monthIndex.toString().padLeft(2, '0');\n  }\n\n  @override\n  String formatFullDate(DateTime date) {\n    final d = date.day.toString().padLeft(2, '0');\n    final m = date.month.toString().padLeft(2, '0');\n    return ' /  / ';\n  }\n\n  @override\n  String formatCompactDate(DateTime date) {\n    final d = date.day.toString().padLeft(2, '0');\n    final m = date.month.toString().padLeft(2, '0');\n    return '//';\n  }\n\n  @override\n  String formatShortDate(DateTime date) {\n    final d = date.day.toString().padLeft(2, '0');\n    final m = date.month.toString().padLeft(2, '0');\n    return '//';\n  }\n\n  @override
  dynamic get openAppDrawerTooltip => (original as dynamic).openAppDrawerTooltip;\n  @override
  dynamic get backButtonTooltip => (original as dynamic).backButtonTooltip;\n  @override
  dynamic get clearButtonTooltip => (original as dynamic).clearButtonTooltip;\n  @override
  dynamic get closeButtonTooltip => (original as dynamic).closeButtonTooltip;\n  @override
  dynamic get deleteButtonTooltip => (original as dynamic).deleteButtonTooltip;\n  @override
  dynamic get moreButtonTooltip => (original as dynamic).moreButtonTooltip;\n  @override
  dynamic get nextMonthTooltip => (original as dynamic).nextMonthTooltip;\n  @override
  dynamic get previousMonthTooltip => (original as dynamic).previousMonthTooltip;\n  @override
  dynamic get firstPageTooltip => (original as dynamic).firstPageTooltip;\n  @override
  dynamic get lastPageTooltip => (original as dynamic).lastPageTooltip;\n  @override
  dynamic get nextPageTooltip => (original as dynamic).nextPageTooltip;\n  @override
  dynamic get previousPageTooltip => (original as dynamic).previousPageTooltip;\n  @override
  dynamic get showMenuTooltip => (original as dynamic).showMenuTooltip;\n  @override
  dynamic get licensesPageTitle => (original as dynamic).licensesPageTitle;\n  @override
  dynamic get rowsPerPageTitle => (original as dynamic).rowsPerPageTitle;\n  @override
  dynamic get cancelButtonLabel => (original as dynamic).cancelButtonLabel;\n  @override
  dynamic get closeButtonLabel => (original as dynamic).closeButtonLabel;\n  @override
  dynamic get continueButtonLabel => (original as dynamic).continueButtonLabel;\n  @override
  dynamic get copyButtonLabel => (original as dynamic).copyButtonLabel;\n  @override
  dynamic get cutButtonLabel => (original as dynamic).cutButtonLabel;\n  @override
  dynamic get scanTextButtonLabel => (original as dynamic).scanTextButtonLabel;\n  @override
  dynamic get okButtonLabel => (original as dynamic).okButtonLabel;\n  @override
  dynamic get pasteButtonLabel => (original as dynamic).pasteButtonLabel;\n  @override
  dynamic get selectAllButtonLabel => (original as dynamic).selectAllButtonLabel;\n  @override
  dynamic get lookUpButtonLabel => (original as dynamic).lookUpButtonLabel;\n  @override
  dynamic get searchWebButtonLabel => (original as dynamic).searchWebButtonLabel;\n  @override
  dynamic get shareButtonLabel => (original as dynamic).shareButtonLabel;\n  @override
  dynamic get viewLicensesButtonLabel => (original as dynamic).viewLicensesButtonLabel;\n  @override
  dynamic get anteMeridiemAbbreviation => (original as dynamic).anteMeridiemAbbreviation;\n  @override
  dynamic get postMeridiemAbbreviation => (original as dynamic).postMeridiemAbbreviation;\n  @override
  dynamic get timePickerHourModeAnnouncement => (original as dynamic).timePickerHourModeAnnouncement;\n  @override
  dynamic get timePickerMinuteModeAnnouncement => (original as dynamic).timePickerMinuteModeAnnouncement;\n  @override
  dynamic get modalBarrierDismissLabel => (original as dynamic).modalBarrierDismissLabel;\n  @override
  dynamic get menuDismissLabel => (original as dynamic).menuDismissLabel;\n  @override
  dynamic get drawerLabel => (original as dynamic).drawerLabel;\n  @override
  dynamic get popupMenuLabel => (original as dynamic).popupMenuLabel;\n  @override
  dynamic get menuBarMenuLabel => (original as dynamic).menuBarMenuLabel;\n  @override
  dynamic get dialogLabel => (original as dynamic).dialogLabel;\n  @override
  dynamic get alertDialogLabel => (original as dynamic).alertDialogLabel;\n  @override
  dynamic get searchFieldLabel => (original as dynamic).searchFieldLabel;\n  @override
  dynamic get currentDateLabel => (original as dynamic).currentDateLabel;\n  @override
  dynamic get selectedDateLabel => (original as dynamic).selectedDateLabel;\n  @override
  dynamic get scrimLabel => (original as dynamic).scrimLabel;\n  @override
  dynamic get bottomSheetLabel => (original as dynamic).bottomSheetLabel;\n  @override
  dynamic get scriptCategory => (original as dynamic).scriptCategory;\n  @override
  dynamic get narrowWeekdays => (original as dynamic).narrowWeekdays;\n  @override
  dynamic get firstDayOfWeekIndex => (original as dynamic).firstDayOfWeekIndex;\n  @override
  dynamic get dateSeparator => (original as dynamic).dateSeparator;\n  @override
  dynamic get dateHelpText => (original as dynamic).dateHelpText;\n  @override
  dynamic get selectYearSemanticsLabel => (original as dynamic).selectYearSemanticsLabel;\n  @override
  dynamic get unspecifiedDate => (original as dynamic).unspecifiedDate;\n  @override
  dynamic get unspecifiedDateRange => (original as dynamic).unspecifiedDateRange;\n  @override
  dynamic get dateInputLabel => (original as dynamic).dateInputLabel;\n  @override
  dynamic get dateRangeStartLabel => (original as dynamic).dateRangeStartLabel;\n  @override
  dynamic get dateRangeEndLabel => (original as dynamic).dateRangeEndLabel;\n  @override
  dynamic get invalidDateFormatLabel => (original as dynamic).invalidDateFormatLabel;\n  @override
  dynamic get invalidDateRangeLabel => (original as dynamic).invalidDateRangeLabel;\n  @override
  dynamic get dateOutOfRangeLabel => (original as dynamic).dateOutOfRangeLabel;\n  @override
  dynamic get saveButtonLabel => (original as dynamic).saveButtonLabel;\n  @override
  dynamic get datePickerHelpText => (original as dynamic).datePickerHelpText;\n  @override
  dynamic get dateRangePickerHelpText => (original as dynamic).dateRangePickerHelpText;\n  @override
  dynamic get calendarModeButtonLabel => (original as dynamic).calendarModeButtonLabel;\n  @override
  dynamic get inputDateModeButtonLabel => (original as dynamic).inputDateModeButtonLabel;\n  @override
  dynamic get timePickerDialHelpText => (original as dynamic).timePickerDialHelpText;\n  @override
  dynamic get timePickerInputHelpText => (original as dynamic).timePickerInputHelpText;\n  @override
  dynamic get timePickerHourLabel => (original as dynamic).timePickerHourLabel;\n  @override
  dynamic get timePickerMinuteLabel => (original as dynamic).timePickerMinuteLabel;\n  @override
  dynamic get invalidTimeLabel => (original as dynamic).invalidTimeLabel;\n  @override
  dynamic get dialModeButtonLabel => (original as dynamic).dialModeButtonLabel;\n  @override
  dynamic get inputTimeModeButtonLabel => (original as dynamic).inputTimeModeButtonLabel;\n  @override
  dynamic get signedInLabel => (original as dynamic).signedInLabel;\n  @override
  dynamic get hideAccountsLabel => (original as dynamic).hideAccountsLabel;\n  @override
  dynamic get showAccountsLabel => (original as dynamic).showAccountsLabel;\n  @override
  dynamic get reorderItemToStart => (original as dynamic).reorderItemToStart;\n  @override
  dynamic get reorderItemToEnd => (original as dynamic).reorderItemToEnd;\n  @override
  dynamic get reorderItemUp => (original as dynamic).reorderItemUp;\n  @override
  dynamic get reorderItemDown => (original as dynamic).reorderItemDown;\n  @override
  dynamic get reorderItemLeft => (original as dynamic).reorderItemLeft;\n  @override
  dynamic get reorderItemRight => (original as dynamic).reorderItemRight;\n  @override
  dynamic get refreshIndicatorSemanticLabel => (original as dynamic).refreshIndicatorSemanticLabel;\n  @override
  dynamic get keyboardKeyAlt => (original as dynamic).keyboardKeyAlt;\n  @override
  dynamic get keyboardKeyAltGraph => (original as dynamic).keyboardKeyAltGraph;\n  @override
  dynamic get keyboardKeyBackspace => (original as dynamic).keyboardKeyBackspace;\n  @override
  dynamic get keyboardKeyCapsLock => (original as dynamic).keyboardKeyCapsLock;\n  @override
  dynamic get keyboardKeyChannelDown => (original as dynamic).keyboardKeyChannelDown;\n  @override
  dynamic get keyboardKeyChannelUp => (original as dynamic).keyboardKeyChannelUp;\n  @override
  dynamic get keyboardKeyControl => (original as dynamic).keyboardKeyControl;\n  @override
  dynamic get keyboardKeyDelete => (original as dynamic).keyboardKeyDelete;\n  @override
  dynamic get keyboardKeyEject => (original as dynamic).keyboardKeyEject;\n  @override
  dynamic get keyboardKeyEnd => (original as dynamic).keyboardKeyEnd;\n  @override
  dynamic get keyboardKeyEscape => (original as dynamic).keyboardKeyEscape;\n  @override
  dynamic get keyboardKeyFn => (original as dynamic).keyboardKeyFn;\n  @override
  dynamic get keyboardKeyHome => (original as dynamic).keyboardKeyHome;\n  @override
  dynamic get keyboardKeyInsert => (original as dynamic).keyboardKeyInsert;\n  @override
  dynamic get keyboardKeyMeta => (original as dynamic).keyboardKeyMeta;\n  @override
  dynamic get keyboardKeyMetaMacOs => (original as dynamic).keyboardKeyMetaMacOs;\n  @override
  dynamic get keyboardKeyMetaWindows => (original as dynamic).keyboardKeyMetaWindows;\n  @override
  dynamic get keyboardKeyNumLock => (original as dynamic).keyboardKeyNumLock;\n  @override
  dynamic get keyboardKeyNumpad1 => (original as dynamic).keyboardKeyNumpad1;\n  @override
  dynamic get keyboardKeyNumpad2 => (original as dynamic).keyboardKeyNumpad2;\n  @override
  dynamic get keyboardKeyNumpad3 => (original as dynamic).keyboardKeyNumpad3;\n  @override
  dynamic get keyboardKeyNumpad4 => (original as dynamic).keyboardKeyNumpad4;\n  @override
  dynamic get keyboardKeyNumpad5 => (original as dynamic).keyboardKeyNumpad5;\n  @override
  dynamic get keyboardKeyNumpad6 => (original as dynamic).keyboardKeyNumpad6;\n  @override
  dynamic get keyboardKeyNumpad7 => (original as dynamic).keyboardKeyNumpad7;\n  @override
  dynamic get keyboardKeyNumpad8 => (original as dynamic).keyboardKeyNumpad8;\n  @override
  dynamic get keyboardKeyNumpad9 => (original as dynamic).keyboardKeyNumpad9;\n  @override
  dynamic get keyboardKeyNumpad0 => (original as dynamic).keyboardKeyNumpad0;\n  @override
  dynamic get keyboardKeyNumpadAdd => (original as dynamic).keyboardKeyNumpadAdd;\n  @override
  dynamic get keyboardKeyNumpadComma => (original as dynamic).keyboardKeyNumpadComma;\n  @override
  dynamic get keyboardKeyNumpadDecimal => (original as dynamic).keyboardKeyNumpadDecimal;\n  @override
  dynamic get keyboardKeyNumpadDivide => (original as dynamic).keyboardKeyNumpadDivide;\n  @override
  dynamic get keyboardKeyNumpadEnter => (original as dynamic).keyboardKeyNumpadEnter;\n  @override
  dynamic get keyboardKeyNumpadEqual => (original as dynamic).keyboardKeyNumpadEqual;\n  @override
  dynamic get keyboardKeyNumpadMultiply => (original as dynamic).keyboardKeyNumpadMultiply;\n  @override
  dynamic get keyboardKeyNumpadParenLeft => (original as dynamic).keyboardKeyNumpadParenLeft;\n  @override
  dynamic get keyboardKeyNumpadParenRight => (original as dynamic).keyboardKeyNumpadParenRight;\n  @override
  dynamic get keyboardKeyNumpadSubtract => (original as dynamic).keyboardKeyNumpadSubtract;\n  @override
  dynamic get keyboardKeyPageDown => (original as dynamic).keyboardKeyPageDown;\n  @override
  dynamic get keyboardKeyPageUp => (original as dynamic).keyboardKeyPageUp;\n  @override
  dynamic get keyboardKeyPower => (original as dynamic).keyboardKeyPower;\n  @override
  dynamic get keyboardKeyPowerOff => (original as dynamic).keyboardKeyPowerOff;\n  @override
  dynamic get keyboardKeyPrintScreen => (original as dynamic).keyboardKeyPrintScreen;\n  @override
  dynamic get keyboardKeyScrollLock => (original as dynamic).keyboardKeyScrollLock;\n  @override
  dynamic get keyboardKeySelect => (original as dynamic).keyboardKeySelect;\n  @override
  dynamic get keyboardKeyShift => (original as dynamic).keyboardKeyShift;\n  @override
  dynamic get keyboardKeySpace => (original as dynamic).keyboardKeySpace;\n  @override
  String aboutListTileTitle(String applicationName) => original.aboutListTileTitle(applicationName);\n  @override
  String licensesPackageDetailText(int licenseCount) => original.licensesPackageDetailText(licenseCount);\n  @override
  String pageRowsInfoTitle(int firstRow, int lastRow, int rowCount, bool rowCountIsApproximate) => original.pageRowsInfoTitle(firstRow, lastRow, rowCount, rowCountIsApproximate);\n  @override
  String tabLabel({required int tabIndex, required int tabCount}) => original.tabLabel(tabIndex: tabIndex, tabCount: tabCount);\n  @override
  String selectedRowCountTitle(int selectedRowCount) => original.selectedRowCountTitle(selectedRowCount);\n  @override
  String scrimOnTapHint(String modalRouteContentName) => original.scrimOnTapHint(modalRouteContentName);\n  @override
  TimeOfDayFormat timeOfDayFormat({bool alwaysUse24HourFormat = false}) => original.timeOfDayFormat(alwaysUse24HourFormat: alwaysUse24HourFormat);\n  @override
  String formatDecimal(int number) => original.formatDecimal(number);\n  @override
  String formatHour(TimeOfDay timeOfDay, {bool alwaysUse24HourFormat = false}) => original.formatHour(timeOfDay, alwaysUse24HourFormat: alwaysUse24HourFormat);\n  @override
  String formatMinute(TimeOfDay timeOfDay) => original.formatMinute(timeOfDay);\n  @override
  String formatTimeOfDay(TimeOfDay timeOfDay, {bool alwaysUse24HourFormat = false}) => original.formatTimeOfDay(timeOfDay, alwaysUse24HourFormat: alwaysUse24HourFormat);\n  @override
  String formatYear(DateTime date) => original.formatYear(date);\n  @override
  String formatShortMonthDay(DateTime date) => original.formatShortMonthDay(date);\n  @override
  DateTime? parseCompactDate(String? inputString) => original.parseCompactDate(inputString);\n  @override
  String dateRangeStartDateSemanticLabel(String formattedDate) => original.dateRangeStartDateSemanticLabel(formattedDate);\n  @override
  String dateRangeEndDateSemanticLabel(String formattedDate) => original.dateRangeEndDateSemanticLabel(formattedDate);\n  @override
  String remainingTextFieldCharacterCount(int remaining) => original.remainingTextFieldCharacterCount(remaining);\n}